### ISSUE TITLE
Fix : AFR (refresh rate) capricious (tvOS)

### ISSUE THREAD

**Issue by JeremTM93** [skrew/lillyplayer-support#29]
After switching between several TV channels in 50fps and 25fps, the AFR is temperamental and may not work afterwards, on VOD and on TV channels.
The only solution is to stop the application and restart.

*Après avoir zappé entre plusieurs chaînes TV en 50fps et 25fps, l'AFR est capricieux et peut ne pas fonctionner ensuite, sur la VOD et sur les chaînes TV.
Seule solution, arrêter l'application et redémarrer.

**Comment by cdguy** [comment]
I've been looking at some of the topics that have been discussed on github about AFR, and I found this piece of code (which says deprecated)
https://developer.apple.com/documentation/avfoundation/avasset/2935636-preferreddisplaycriteria?language=swift
https://developer.apple.com/documentation/avfoundation/avasset/2935636-preferreddisplaycriteria?language=objc

https://github.com/kingslay/KSPlayer/issues/307
https://github.com/kingslay/KSPlayer/issues/308

I wonder if the problem is due to the "old code" to activate the AFR? @skrewzz

because according to what I read, some users have no problem, others do a "kill app" to correct the problem, and I have the problem of the player going to the next channel without me wanting it

**Comment by skrew** [comment]
don't forget to specify the player lib

**Comment by JeremTM93** [comment]
> don't forget to specify the player lib 

Found with KSLib. I let other users confirmed the problem with MPVlib.

**Comment by skrew** [comment]
I changed the AFR management in Lillyplayer and I let KS manage the AFR 100% by itself.
If it's still not good in the 2.6.2 version, re-open the ticket.

**Comment by skrew** [comment]
check in 2.6.5
